### PR TITLE
TDE validation now works on ML versions < 10.0-9

### LINKED ISSUE #149: TDE validation is skipped on ML < 10.0-9
PR #144 disabled TDE validation in all cases. This works fine on ML 10.0-9 or higher because TDE validation will be handled by the batch insert call. But the feature doesn't work on ML < 10.0-9. 

We currently have this logic:

```
                 if(isTdeTemplate) {
			return documentFile;
		}

		if (isTdeTemplate) {
			if(helper.getMLEffectiveVersion() >= 10000900 && tdeValidationDatabase != null && !tdeValidationDatabase.isEmpty()) {
				return documentFile;
			} else {
				validateTdeTemplate(documentFile);
			}
		}
```

The first block should be removed, and then I think `validateTdeTemplate` simply needs to say - if this is ML 10.0-9 or higher, don't bother, because we know that batch insert will be used and that will perform its own TDE validation.

### PR DESCRIPTION
**Pull request by rjrudin**
Resolves #149. Also fixed a problem where with ML version >= 10.0-9, all schema files were being passed into the templateBatchInsert function. Added a test to verify that this no longer occurs. 

Also added TdeUtil to store util/constant stuff for TDE functionality.

### CODE REVIEW

**Comment by rjrudin** [comment]
The schemas tests should now pass on both ML 10.0-9 and ML 10.0-8 . The tests did not pass before on 10.0-8 because TDE validation was disabled unless templateBatchInsert was present.

File: src/main/java/com/marklogic/client/ext/file/DocumentFile.java [hunk 1]
```diff
@@ -65,7 +64,7 @@ public DocumentWriteOperation.OperationType getOperationType() {
 		return DocumentWriteOperation.OperationType.DOCUMENT_WRITE;
 	}
 
-	public DocumentMetadataWriteHandle getMetadata() {
+	public DocumentMetadataHandle getMetadata() {
```
Comment (rjrudin) [inline src/main/java/com/marklogic/client/ext/file/DocumentFile.java:67]: Not sure why I had this returning the fairly useless abstract type; the value is always an instance of `DocumentMetadataHandle`. Needed this change so that `DefaultSchemasLoader` can determinate if a file is a TDE template or not based on collections.

File: src/main/java/com/marklogic/client/ext/helper/ClientHelper.java [hunk 2]
```diff
@@ -68,14 +66,4 @@ public String eval(String expr) {
         return getClient().newServerEval().xquery(expr).evalAs(String.class);
     }
 
-    public int getMLEffectiveVersion() {
```
Comment (rjrudin) [inline src/main/java/com/marklogic/client/ext/helper/ClientHelper.java:71]: Replaced this in favor of the smaller-scoped function in `TdeUtil`.

File: src/main/java/com/marklogic/client/ext/schemasloader/impl/DefaultSchemasLoader.java [hunk 3]
```diff
@@ -84,11 +84,27 @@ protected void initializeDefaultSchemasLoader() {
...
+			for (DocumentFile file : documentFiles) {
+				DocumentMetadataHandle metadata = file.getMetadata();
+				if (metadata != null && metadata.getCollections().contains(TdeUtil.TDE_COLLECTION)) {
+					tdeFiles.add(file);
+				} else {
+					nonTdeFiles.add(file);
+				}
+			}
+
+			if (!tdeFiles.isEmpty()) {
```
Comment (rjrudin) [inline src/main/java/com/marklogic/client/ext/schemasloader/impl/DefaultSchemasLoader.java:101]: Only passing TDE files now into the new function

File: src/test/java/com/marklogic/client/ext/schemasloader/impl/ValidateTdeTemplatesTest.java [hunk 4]
```diff
@@ -27,9 +27,20 @@ public void setup() {
 
 	@Test
 	public void badJsonFile() {
-		FailedRequestException ex = assertThrows(FailedRequestException.class, () ->
-			loader.loadSchemas(Paths.get("src", "test", "resources", "bad-schemas", "bad-json").toString()));
-		logger.info(ex.getMessage());
+		final String path = Paths.get("src", "test", "resources", "bad-schemas", "bad-json").toString();
```
Comment (rjrudin) [inline src/test/java/com/marklogic/client/ext/schemasloader/impl/ValidateTdeTemplatesTest.java:30]: Need different assertions based on whether templateBatchInsert is supported or not.

**Review by BillFarber — APPROVED** [review]

**Review by rahulvudutala — APPROVED** [review]
